Added Games statistics screens to QudUX
egocarib/CavesOfQud-QudUX-v2 pull request #2
Opened 2020-10-09 06:32 UTC by oschwab

Several comments:

- No real code guidelines (and not many comments ...) used, only my numerous years of C# habits
- I've created the _Table_ class to ease the management of tables, and I've added it to ConsoleUtilies.cs . I don't know if it is pertinent.
- I've added a SingleBoxDivider method that allow to choose the height of the divider
- I've kept my PlayerMutator and LoadGameHandler , but I bet  they're useless now
- I've tested it , it works except a strange error when trying to define the key of the screen

See you.

2020-10-10 00:28 UTC, egocarib requested changes
Very nice work overall! I tested this in game and everything seems to be working great. I didn't have any issues setting up my Key Mapping either (no weird errors).

I've proposed a number of changes. Feel free to adjust as you see fit and re-submit for review. 👍

2020-10-10 00:28 UTC, egocarib commented on Screens/QudUX_GameStatsScreen.cs
> +					}
Suggestion to also support PageUp and PageDown keys
```suggestion
					if (keys == Keys.NumPad3 || keys == Keys.Next)
					{
						currentTable.ScrollPage(1);
					}

					if (keys == Keys.NumPad9 || keys == Keys.Prior)
					{
						currentTable.ScrollPage(-1);
					}
```

2020-10-10 00:28 UTC, egocarib commented on Utilities/ConsoleUtilities.cs
> +        public void Scroll (int direction)
Does the `Scroll` method do anything? If not, consider deleting it to avoid confusing anyone about whether to use it later. 😄

2020-10-10 00:28 UTC, egocarib commented on Utilities/ConsoleUtilities.cs
> +                Offset += (direction * MaxVisibleRows);
There is a minor bug where if you scroll from the second-last page to the final page while your SelectedIndex is lower than the final entry, the selection caret (>) disappears until you press NumPad8 or Numpad2.

Checking if SelectedIndex is still valid after ScrollPage would be a nice fix. (Up to you if you want to fix it since it's a pretty minor detail, and nothing _bad_ happens.)

2020-10-10 00:28 UTC, egocarib commented on Utilities/ConsoleUtilities.cs
>          }
Optional: You could make the existing `SingleBoxVerticalDivider` function call your new version instead of performing almost duplicate code.

2020-10-10 00:28 UTC, egocarib commented on Screens/QudUX_GameStatsScreen.cs
> +						where !s.Abandoned
Filtering out abandoned games actually confused me, because I didn't see some of the high scores I knew should be in the list (and my list wasn't as long as I expected it to be, based on looking at the game's default High Scores menu).

I know someone mentioned this on Discord, but I disagree with completely filtering them out. I would recommend either of the following options:
1. Don't filter them out.
2. Add a button in the Gamestats menu that lets someone toggle whether they are shown. This allows the user to choose whether or not to hide them and avoids confusion.

2020-10-10 14:21 UTC, oschwab commented on Utilities/ConsoleUtilities.cs
> +        public void Scroll (int direction)
It is a general function to scroll  the table of 1 line instead of 1 page.
I think it doen't harm to let it there even if it is not used for now.

2020-10-10 14:34 UTC, oschwab commented on Utilities/ConsoleUtilities.cs
> +                Offset += (direction * MaxVisibleRows);
I'll correct it :)

2020-10-10 17:37 UTC, oschwab commented on Parts and Effects/QudUX_EnhancedScoreBoard.cs
> +
Done.

2020-10-11 20:02 UTC, oschwab commented on Screens/QudUX_GameStatsScreen.cs
> +						where !s.Abandoned
I temporary count them again, and will add later the option to take them in account.

2020-10-11 20:11 UTC, oschwab commented
That was my first PR since a long time, so I hope I did not make any mistakes. All should be in the correct situation now.

2020-10-14 00:04 UTC, egocarib commented on Screens/QudUX_GameStatsScreen.cs
> +					if (keys == (Keys)131137)
Replace number with Keys enum LogicalOr
```suggestion
					if (keys == (Keys.Control | Keys.A))
```

2020-10-14 00:05 UTC, egocarib approved these changes
Looks good now.

2020-10-20 23:07 UTC, merged